// Package conditions implements the RbacPolicy advanced match DSL. The
// Condition struct is embedded in pkg/apis/rbacreports/v1alpha1.Match,
// so DeepCopy methods are needed here as well — they are generated by
// `controller-gen object` from the marker on the package clause.

// +kubebuilder:object:generate=true
package conditions
